# add stages here 
stages:
  prepare_data:
    cmd: python src/stage_01_prepare.py
    deps:
      - src/stage_01_prepare.py
      - data/data.xml
      - src/utils/common.py
      - src/utils/data_mgmt.py
      - configs/config.yaml
    params:
      - prepare.seed
      - prepare.split
    outs:
      - artifacts/prepared/train.tsv
      - artifacts/prepared/test.tsv

  featurize:
    cmd: python src/stage_02_featurization.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_02_featurization.py
      - artifacts/prepared/train.tsv
      - artifacts/prepared/test.tsv
      - src/utils/common.py
      - src/utils/featurize.py
      - configs/config.yaml
    params:
      - featurize.max_features
      - featurize.ngrams
    outs:
      - artifacts/features/train.pkl
      - artifacts/features/test.pkl

  train:
    cmd: python src/stage_03_train.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_03_train.py
      - artifacts/features/train.pkl
      - src/utils/common.py
      - configs/config.yaml
    params:
      - train.seed
      - train.n_est
      - train.min_split
    outs:
      - artifacts/model/model.pkl
